/*
 * This source file was generated by the Gradle 'init' task
 */
package org.co;

import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.JLabel;

import org.co.components.dave_buttons;

public class App extends JFrame {
    private final JLabel label_title;

    public App() {
        setPreferredSize(new Dimension(400, 500));
        setVisible(true);
        label_title = new JLabel("Base Converter");
        var btns = new dave_buttons();
        add(label_title);
        add(btns);
        pack();
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var app = new App();
        System.out.println(app.getGreeting());
    }
}
