/*
 * This source file was generated by the Gradle 'init' task
 */
package org.co;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.co.components.base_buttons;
import org.co.components.dave_textfield;
import org.co.utils.base_conversion;

/**
 * main app
 */
public class App extends JFrame {
    private final JLabel label_title;
    private final JButton btn_calc;
    private final base_buttons btns_input_base, btns_output_base;
    private final dave_textfield txt_input, txt_output;
    private final JPanel panel = new JPanel();

    /**
     * initializes components and do basic setups
     */
    public App() {
        setVisible(true);
        setPreferredSize(new Dimension(400, 500));
        txt_input = new dave_textfield("Number to be Converted: ", false);
        txt_output = new dave_textfield("Converted Number: ", true);
        label_title = new JLabel("Base Converter");
        label_title.setFont(new Font("title_font", Font.BOLD, 24));
        label_title.setForeground(Color.red);
        btns_input_base = new base_buttons("Input Number Base");
        btns_output_base = new base_buttons("Output Number Base");
        btn_calc = new JButton("Calculate");
        btn_calc.addActionListener((ActionEvent e) -> {
            if (txt_input.get_text().isBlank()) {
                return;
            }
            txt_output.reset(); 
            String output = calculate_output();
            txt_output.set_text(output);
        });
        panel.add(label_title);
        panel.add(txt_input);
        panel.add(btns_input_base);
        panel.add(btns_output_base);
        panel.add(btn_calc);
        panel.add(txt_output);
        add(panel);
        pack();
    }

    /**
     * converts input into a desired base
     * @return
     */
    private String calculate_output() {
        var input_base = btns_input_base.selected_base;
        var output_base = btns_output_base.selected_base;
        int input = (int) txt_input.get_value();
        return base_conversion.convert_base(input, input_base, output_base);
    }

    /**
     * Tests app build
     * @return
     */
    public String getGreeting() {
        return "App build is successful.";
    }

    /**
     * starts program
     * @param args arguments in terminal
     */
    public static void main(String[] args) {
        var app = new App();
        System.out.println(app.getGreeting());
    }
}
